// Code generated by dnsroot DO NOT EDIT.
// ----------------------------------------------------------------
// dnsroot version:  0.0.1
// dnsroot update:   2023-04-12
// InterNIC version: 2023032901
// InterNIC update:  2023-03-29
// ----------------------------------------------------------------

package main


import "net"

type RootServer struct {
	Name       string
	Formerly   string
	OperatedBy string
	A          net.IP
	AAAA       net.IP
}