// Code generated by dnsroot DO NOT EDIT.
// ----------------------------------------------------------------
// dnsroot version:  0.0.1
// dnsroot update:   2023-04-12
// InterNIC version: 2023032901
// InterNIC update:  2023-03-29
// ----------------------------------------------------------------

package main


import "net"

type RootServer struct {
	Name       string
	Formerly   string
	OperatedBy string
	A          net.IP
	AAAA       net.IP
}

var _rootServers = []*RootServer{
    {
		Name:       "A.ROOT-SERVERS.NET",
		Formerly:   "NS.INTERNIC.NET",
		OperatedBy: "",
		A:          net.ParseIP("198.41.0.4"),
		AAAA:       net.ParseIP("2001:503:ba3e::2:30"),
	},
    {
		Name:       "B.ROOT-SERVERS.NET",
		Formerly:   "NS1.ISI.EDU",
		OperatedBy: "",
		A:          net.ParseIP("199.9.14.201"),
		AAAA:       net.ParseIP("2001:500:200::b"),
	},
    {
		Name:       "C.ROOT-SERVERS.NET",
		Formerly:   "C.PSI.NET",
		OperatedBy: "",
		A:          net.ParseIP("192.33.4.12"),
		AAAA:       net.ParseIP("2001:500:2::c"),
	},
    {
		Name:       "D.ROOT-SERVERS.NET",
		Formerly:   "TERP.UMD.EDU",
		OperatedBy: "",
		A:          net.ParseIP("199.7.91.13"),
		AAAA:       net.ParseIP("2001:500:2d::d"),
	},
    {
		Name:       "E.ROOT-SERVERS.NET",
		Formerly:   "NS.NASA.GOV",
		OperatedBy: "",
		A:          net.ParseIP("192.203.230.10"),
		AAAA:       net.ParseIP("2001:500:a8::e"),
	},
    {
		Name:       "F.ROOT-SERVERS.NET",
		Formerly:   "NS.ISC.ORG",
		OperatedBy: "",
		A:          net.ParseIP("192.5.5.241"),
		AAAA:       net.ParseIP("2001:500:2f::f"),
	},
    {
		Name:       "G.ROOT-SERVERS.NET",
		Formerly:   "NS.NIC.DDN.MIL",
		OperatedBy: "",
		A:          net.ParseIP("192.112.36.4"),
		AAAA:       net.ParseIP("2001:500:12::d0d"),
	},
    {
		Name:       "H.ROOT-SERVERS.NET",
		Formerly:   "AOS.ARL.ARMY.MIL",
		OperatedBy: "",
		A:          net.ParseIP("198.97.190.53"),
		AAAA:       net.ParseIP("2001:500:1::53"),
	},
    {
		Name:       "I.ROOT-SERVERS.NET",
		Formerly:   "NIC.NORDU.NET",
		OperatedBy: "",
		A:          net.ParseIP("192.36.148.17"),
		AAAA:       net.ParseIP("2001:7fe::53"),
	},
    {
		Name:       "J.ROOT-SERVERS.NET",
		Formerly:   "",
		OperatedBy: "VERISIGN, INC.",
		A:          net.ParseIP("192.58.128.30"),
		AAAA:       net.ParseIP("2001:503:c27::2:30"),
	},
    {
		Name:       "K.ROOT-SERVERS.NET",
		Formerly:   "",
		OperatedBy: "RIPE NCC",
		A:          net.ParseIP("193.0.14.129"),
		AAAA:       net.ParseIP("2001:7fd::1"),
	},
    {
		Name:       "L.ROOT-SERVERS.NET",
		Formerly:   "",
		OperatedBy: "ICANN",
		A:          net.ParseIP("199.7.83.42"),
		AAAA:       net.ParseIP("2001:500:9f::42"),
	},
    {
		Name:       "M.ROOT-SERVERS.NET",
		Formerly:   "",
		OperatedBy: "WIDE",
		A:          net.ParseIP("202.12.27.33"),
		AAAA:       net.ParseIP("2001:dc3::35"),
	},
}